CREATE TABLE seating_chart (
    FLOOR_SEAT_SEQ INT PRIMARY KEY AUTO_INCREMENT,
    FLOOR_NO INT NOT NULL,
    SEAT_NO VARCHAR(10) NOT NULL
);

CREATE TABLE employee (
    EMP_ID INT PRIMARY KEY,
    NAME VARCHAR(100),
    EMAIL VARCHAR(100),
    FLOOR_SEAT_SEQ INT,
    FOREIGN KEY (FLOOR_SEAT_SEQ) REFERENCES seating_chart(FLOOR_SEAT_SEQ)
);